import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import { saveComposeDraft, readComposeDraft, offerGuestDraft, claimGuestDraft } from "./assistant-draft";
const source = (file: string) => readFileSync(file, "utf8");
function storage(): Storage { const values = new Map<string,string>(); return {get length(){return values.size;},clear:()=>values.clear(),key:(index:number)=>[...values.keys()][index]??null,getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value);},removeItem:(key:string)=>{values.delete(key);}}; }
describe("compact interface regression", () => {
  it("keeps icon actions accessible without duplicate create buttons", () => { const web=source("src/components/personal-agent-dashboard.tsx"),mobile=source("mobile-shell/index.html"); expect(web.includes('<ActionIcon name="settings"')).toBe(true);expect(web.includes('<ActionIcon name="bell"')).toBe(true);expect(web.includes('<ActionIcon name="plus"')).toBe(true);expect(mobile.includes('title="برنامه جدید"')).toBe(true);expect(mobile.includes('class="round-button" data-open-form')).toBe(false); });
  it("removes unsolicited advice and blocks only account-required submission",()=>{const web=source("src/components/personal-agent-dashboard.tsx"),assistant=source("src/components/agent-assistant.tsx"); for(const text of ["اینجا فعلاً خلوت است","زمانی برای استراحت بگذار","برنامه‌ات آزاد است"])expect(web.includes(text)).toBe(false);expect(assistant.includes('disabled={!session')).toBe(false);expect(assistant.includes('setNeedsAccount(true);return;')).toBe(true);expect(assistant.includes('rows={1}')).toBe(true);});
  it("uses the same self-contained recorder in the APK",()=>{expect(source("mobile-shell/voice-capture.js").includes("createVoiceCapture")).toBe(true);expect(source("mobile-shell/connection-error.html").includes("window.HamrahCapture")).toBe(true);expect(source("src/lib/voice-capture.ts")).not.toMatch(/fetch\(|localStorage|sessionStorage/);});
  it("passes explicit rememberMe through both login paths without storing a password",()=>{const login=source("src/components/login-form.tsx");expect(login.includes('name="rememberMe"')).toBe(true);expect(login.includes("password, rememberMe")).toBe(true);expect(login).not.toMatch(/(?:localStorage|sessionStorage)\.setItem/);});
});
describe("tab-scoped compose draft",()=>{
  it("preserves Unicode and separates private accounts",()=>{const s=storage();saveComposeDraft("guest","جلسه فردا",s);saveComposeDraft("user-a","خصوصی",s);expect(readComposeDraft("guest",s)).toBe("جلسه فردا");expect(readComposeDraft("user-b",s)).toBe("");expect(claimGuestDraft(s)).toBe("");offerGuestDraft(s);expect(claimGuestDraft(s)).toBe("جلسه فردا");expect(claimGuestDraft(s)).toBe("");});
  it("expires and bounds persisted text",()=>{const s=storage();saveComposeDraft("guest","x".repeat(3000),s);expect(readComposeDraft("guest",s)).toHaveLength(2000);const now=Date.now();vi.spyOn(Date,"now").mockReturnValue(now+31*60000);expect(readComposeDraft("guest",s)).toBe("");vi.restoreAllMocks();});
  it("keeps unavailable storage non-fatal",()=>{const s={getItem:()=>{throw Error();},setItem:()=>{throw Error();},removeItem:()=>{throw Error();}} as unknown as Storage;expect(()=>saveComposeDraft("guest","سلام",s)).not.toThrow();expect(readComposeDraft("guest",s)).toBe("");expect(claimGuestDraft(s)).toBe("");});
});
