allowBuilds:
  '@prisma/engines': true
  better-sqlite3: true
  prisma: true
  sharp: false
  unrs-resolver: false
overrides:
  deepmerge-ts: 8.0.0
  mysql2: 3.23.1
patchedDependencies:
  '@capacitor/android@8.5.0': patches/@capacitor__android@8.5.0.patch
